language: python
notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
           PLAT=manylinux2010_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

before_install:
  - chmod 755 tools/travis_linux_steps.sh

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/tools/travis_linux_steps.sh

deploy:
  provider: testpypi
  username: "__token__"
  password: $PYPI_TOKEN
  distributions: "sdist bdist_wheel"
#  server:
  skip_existing: true
