language: python

notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686 PLAT=manylinux1_i686 OS=linux
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux1_x86_64 OS=linux


before_install:
  - export RECKIT_VER=0.1.0
  - export TRAVIS_TAG="${OS}_whl-v${RECKIT_VER}-b${TRAVIS_BUILD_NUMBER}"
  - export ZIP_FILE="${OS}_whl-v${RECKIT_VER}-${PLAT}-b${TRAVIS_BUILD_NUMBER}.tar.gz"
  - chmod 755 tools/travis_linux_build_whl.sh
  - chmod 755 tools/travis_osx_build_whl.sh
  - chmod 755 tools/travis_run.sh

#install:
#  - docker pull $DOCKER_IMAGE

script:
  - source tools/travis_run.sh
#  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/tools/travis_linux_build_whl.sh

before_deploy:
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - tar -zcvf ${ZIP_FILE} dist/*

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ${ZIP_FILE}
  skip_cleanup: true
  draft: true
