language: python
notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686
           PLAT=manylinux2010_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

before_install:
  - chmod 755 tools/travis_linux_steps.sh

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -e PYPI_TOKEN=$PYPI_TOKEN -v `pwd`:/io $DOCKER_IMAGE /io/tools/travis_linux_steps.sh

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDMwM2I0NThlLTcyMTktNDg0ZS04YmI2LTczZWJmNjlmZTZiMwACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgRoQTP7Prdg_s9__Bq6fLRmNO3PQmlBRRuCxML2bmuBc"
#    secure: $PYPI_TOKEN
  distributions: sdist bdist_wheel
#  server:
  skip_existing: true
