language: python
notifications:
  email: false
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_i686 PLAT=manylinux2010_i686
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
before_install:
- chmod 755 tools/travis_linux_steps.sh
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -e PLAT=$PLAT -e PYPI_TOKEN=$PYPI_TOKEN -v `pwd`:/io $DOCKER_IMAGE
  /io/tools/travis_linux_steps.sh
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "cIwwWX+UlsdCiivtnpqdbh/glGJWpQK4eft34H7ZSg25qpcD8a1dgLymzfjtcdRBUtCSgCktvEwNNTzy+Y6R/DvCMvaKbRc3h8CoR9DbY9MJSRQAVoWWwpFutgipwU0KK2G9A4F/6K8I5T0y95wA+X9aa8rq/gJWNTiQv5RDdFzuLBo86p4ztofhZbLEH1a69B6UxIjt/AFI6R+e8EwO3cERKZnyjtq4bhjbl6H+rHDMmv7M4+OLLSQn0M+wHDsdqKIcDVfWWH3yXW7K05T4HxdaCFsVycB1KnAlAUKBmutWXzKkGGS1AX0hYuv5xJOQcGWOBym33OX4wRA83/EKDu1Vgsqr4/SrYXYQvgn4NxAxw5lPhWjvptufKndYhHJIxo0ETD1vM8jDq8/z3TZWpItJ+xO2zr44vvHM6RWCfKswBJysopxJo8T/ubk3aDU907R6jgez8VFUJPTt5Tcn8OxVfC6DZhhJ4l4oWQ78PYoCoBkTFCcvF2xb2bdzpI/WqiF5An0kQEP7WKZk+lrl3ZYksjYsRZxrfEPOWK/wxzLSUovLdhMB43ZrCYfum/rpBzHRYrw8P3v+e7PC3srfd/6Qlqp2uOnpc4gViYIxD20Mo3Oc2tSqi4808vuFnS9c8NSAl+s8o+aJVFnOczu+qP32UPw4/K7MqIs5BYgY5qI="
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
